package com.centralizedData.centralized.dto.admin;

import java.time.Instant;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CandidateMarkNewDto {

	private Integer id;
	private String subject1;
	private String subject2;
	private String subject3;
	private String subject4;
	private String subject5;
	private String subject6;
	private String subject7;
	private String subject8;
	private String subject9;
	private String subject10;
	private String subject11;
	private String subject12;
	private String subject13;
	private String subject14;
	private String subject15;
	private String subject16;
	private String subject17;
	private String subject18;
	private String subject19;
	private String subject20;
	private String subject1TotalMarks;
	private String subject2TotalMarks;
	private String subject3TotalMarks;
	private String subject4TotalMarks;
	private String subject5TotalMarks;
	private String subject6TotalMarks;
	private String subject7TotalMarks;
	private String subject8TotalMarks;
	private String subject9TotalMarks;
	private String subject10TotalMarks;
	private String subject11TotalMarks;
	private String subject12TotalMarks;
	private String subject13TotalMarks;
	private String subject14TotalMarks;
	private String subject15TotalMarks;
	private String subject16TotalMarks;
	private String subject17TotalMarks;
	private String subject18TotalMarks;
	private String subject19TotalMarks;
	private String subject20TotalMarks;
	private String subject1ObtainedMarks;
	private String subject2ObtainedMarks;
	private String subject3ObtainedMarks;
	private String subject4ObtainedMarks;
	private String subject5ObtainedMarks;
	private String subject6ObtainedMarks;
	private String subject7ObtainedMarks;
	private String subject8ObtainedMarks;
	private String subject9ObtainedMarks;
	private String subject10ObtainedMarks;
	private String subject11ObtainedMarks;
	private String subject12ObtainedMarks;
	private String subject13ObtainedMarks;
	private String subject14ObtainedMarks;
	private String subject15ObtainedMarks;
	private String subject16ObtainedMarks;
	private String subject17ObtainedMarks;
	private String subject18ObtainedMarks;
	private String subject19ObtainedMarks;
	private String subject20ObtainedMarks;
	private DetailedSubjectsDto detailedSubjects1;
	private DetailedSubjectsDto detailedSubjects2;
	private DetailedSubjectsDto detailedSubjects3;
	private DetailedSubjectsDto detailedSubjects4;
	private DetailedSubjectsDto detailedSubjects5;
	private DetailedSubjectsDto detailedSubjects6;
	private DetailedSubjectsDto detailedSubjects7;
	private DetailedSubjectsDto detailedSubjects8;
	private DetailedSubjectsDto detailedSubjects9;
	private DetailedSubjectsDto detailedSubjects10;
	private DetailedSubjectsDto detailedSubjects11;
	private DetailedSubjectsDto detailedSubjects12;
	private DetailedSubjectsDto detailedSubjects13;
	private DetailedSubjectsDto detailedSubjects14;
	private DetailedSubjectsDto detailedSubjects15;
	private DetailedSubjectsDto detailedSubjects16;
	private DetailedSubjectsDto detailedSubjects17;
	private DetailedSubjectsDto detailedSubjects18;
	private DetailedSubjectsDto detailedSubjects19;
	private DetailedSubjectsDto detailedSubjects20;
	private String overallTotal;
	private String totalMarks;
	private String totalObtainedMarks;
	private boolean lastExam;
	private boolean semesterMark;
	private boolean populated;
	private String createdBy;
	private Instant createdDate;

	private String subject1_languagewise_TotalMarks;
	private String subject2_languagewise_TotalMarks;
	private String subject3_languagewise_TotalMarks;
	private String subject4_languagewise_TotalMarks;
	private String subject5_languagewise_TotalMarks;
	private String subject6_languagewise_TotalMarks;
	private String subject7_languagewise_TotalMarks;
	private String subject8_languagewise_TotalMarks;
	private String subject9_languagewise_TotalMarks;
	private String subject10_languagewise_TotalMarks;

	private String subject1_languagewise_ObtainedMarks;
	private String subject2_languagewise_ObtainedMarks;
	private String subject3_languagewise_ObtainedMarks;
	private String subject4_languagewise_ObtainedMarks;
	private String subject5_languagewise_ObtainedMarks;
	private String subject6_languagewise_ObtainedMarks;
	private String subject7_languagewise_ObtainedMarks;
	private String subject8_languagewise_ObtainedMarks;
	private String subject9_languagewise_ObtainedMarks;
	private String subject10_languagewise_ObtainedMarks;

	private String total_languagewise_Marks;
	private String total_languagewise_ObtainedMarks;

	private boolean subject1Mandatory;
	private boolean subject2Mandatory;
	private boolean subject3Mandatory;
	private boolean subject4Mandatory;
	private boolean subject5Mandatory;
	private boolean subject6Mandatory;
	private boolean subject7Mandatory;
	private boolean subject8Mandatory;
	private boolean subject9Mandatory;
	private boolean subject10Mandatory;
	private boolean subject11Mandatory;
	private boolean subject12Mandatory;
	private boolean subject13Mandatory;
	private boolean subject14Mandatory;
	private boolean subject15Mandatory;
	private boolean subject16Mandatory;
	private boolean subject17Mandatory;
	private boolean subject18Mandatory;
	private boolean subject19Mandatory;
	private boolean subject20Mandatory;
}
